/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "register": [],
    "dashboard": [],
    "logout": [],
    "projects.index": [],
    "projects.store": [],
    "projects.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.transition": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "conversations.messages": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "conversation",
            "required": true,
            "binding": "id"
        }
    ],
    "conversations.send": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "conversation",
            "required": true,
            "binding": "id"
        }
    ],
    "conversations.stream": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "conversation",
            "required": true,
            "binding": "id"
        }
    ],
    "conversations.extract": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "conversation",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.context.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.context.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.requirements.index": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.requirements.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.requirements.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "requirement",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.requirements.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "requirement",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.prd.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.prd.generate": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.prd.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.prd.sections.reorder": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.prd.sections.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "section",
            "required": true
        }
    ],
    "projects.prd.sections.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "section",
            "required": true
        }
    ],
    "projects.prd.sections.ai": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "section",
            "required": true
        }
    ],
    "projects.prd.sections.apply": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "section",
            "required": true
        }
    ],
    "projects.prd.review": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.prd.versions.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.prd.versions.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "versionId",
            "required": true
        }
    ],
    "settings.providers": [],
    "ai.providers.index": [],
    "ai.providers.store": [],
    "ai.providers.update": [
        {
            "name": "provider",
            "required": true,
            "binding": "id"
        }
    ],
    "ai.providers.destroy": [
        {
            "name": "provider",
            "required": true,
            "binding": "id"
        }
    ],
    "ai.providers.test": [
        {
            "name": "provider",
            "required": true,
            "binding": "id"
        }
    ],
    "ai.providers.test-unsaved": [],
    "ai.providers.models": [
        {
            "name": "provider",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
